image: Ubuntu2204  # образ для сборки

stack: node 20  # окружение

branches:
  only:
    - master  # ветка git
    - main

cache: node_modules  # кеширование

install:
  - yarn  # команда установки зависимостей

build: off  # отключаем встроенную в appveyor систему сборки

build_script:
  - yarn build   # команда сборки

test_script:
  - yarn lint 
  - yarn test
  # ЗАПУСКАЕМ СЕРВЕР ДЛЯ E2E ТЕСТОВ
  - yarn start &  # запускаем сервер в фоне
  - sleep 10      # ждем 10 секунд пока сервер запустится
  - yarn e2e      # запускаем E2E тесты


